Repository AY2324S1-CS2103-F13-2/tp, pull requests merged in 2023-10, with the labels that each got.

#50 Edited ReadME to suit HR Insight
  README.md
Labels: documentation

#77 Increase test coverage for ListCommand related classes and methods
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/model/person/MatchingDepartmentPredicateTest.java
Labels: enhancement

#96 Update UG and DG for undo/redo
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#98 Fixed DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#99 Improve help command
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: enhancement

#100 Update user guide
  docs/UserGuide.md
Labels: documentation

#110 Fix edit bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: bug

#108 Add sort command
  .gitignore
  Exported_CSVs/engineering_dept.csv
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Money.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/PersonComparator.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: enhancement

#111 Improve name constraint
  docs/UserGuide.md
  src/main/resources/images/address_book_32.png
  src/test/java/seedu/address/model/person/NameTest.java
Labels: bug, documentation
