Repository AY2324S1-CS2103-F13-2/tp, pull requests merged in 2023-11, with the labels that each got.

#126 Gets previous input
  docs/UserGuide.md
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
Labels: enhancement

#128 Fix UG formatting
  docs/UserGuide.md
Labels: documentation

#136 Fix bug invalid months
  src/main/java/seedu/address/logic/parser/BirthdayCommandParser.java
  src/main/java/seedu/address/model/person/Month.java
  src/test/java/seedu/address/logic/parser/BirthdayCommandParserTest.java
  src/test/java/seedu/address/model/person/MonthTest.java
Labels: bug

#168 Redefine same person
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: bug, enhancement

#169 Fix PED Bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClaimCommand.java
  src/test/java/seedu/address/logic/commands/ClaimCommandTest.java
Labels: bug, documentation

#172 Fix leave
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/LeaveCommand.java
  src/main/java/seedu/address/logic/parser/LeaveCommandParser.java
  src/test/java/seedu/address/logic/parser/LeaveCommandParserTest.java
Labels: documentation

#175 Updated User Guide
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Name.java
Labels: documentation

#176 Modified and added ss
  docs/UserGuide.md
  docs/images/BirthdayAfter.png
  docs/images/BirthdayBefore.png
  docs/images/ClaimAfter.png
  docs/images/ClaimBefore.png
  docs/images/DeleteEmployeeAfter.png
  docs/images/DeleteEmployeeBefore.png
  docs/images/EditEmployeeAfter.png
  docs/images/EditEmployeeBefore.png
  docs/images/FindEmployeeAfter.png
  docs/images/FindEmployeeBefore.png
  docs/images/LeaveEmployeeAfter.png
  docs/images/LeaveEmployeeBefore.png
  docs/images/ListEmployeesAfter.png
  docs/images/ListEmployeesBefore.png
  docs/images/ResetLeaveAfter.png
  docs/images/ResetLeaveBefore.png
  docs/images/ViewLeaveAfter.png
  docs/images/ViewLeaveBefore.png
Labels: documentation

#185 Update UG DG
  Exported_CSVs/testExport.csv
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: documentation

#189 Fix wrong background color bug GUI
  src/main/resources/view/BlueTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/GreenTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/RedTheme.css
Labels: bug

#191 Upload redo diagram
  docs/diagrams/RedoSequenceDiagram.puml
Labels: documentation

#190 Updated UG and DG.
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/RedoSequenceDiagram.png
  docs/images/UndoSequenceDiagram.png
Labels: documentation

#202 Fix grammar
  docs/DeveloperGuide.md
Labels: documentation

#203 Fix grammar
  docs/UserGuide.md
Labels: documentation

#204 Fix PPP
  docs/team/nixonwidjaja.md
Labels: documentation

#205 Fix phone bug
  src/main/java/seedu/address/model/person/Phone.java
Labels: bug

#206 Fix leave bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/LeaveCommandParser.java
Labels: bug

#208 Update DeveloperGuide
  docs/DeveloperGuide.md
Labels: documentation

#210 Minor UG updates
  docs/UserGuide.md
Labels: documentation

#212 Fix claim bug
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ClaimCommandParserTest.java
Labels: bug
